### PR TITLE
Allow previewing your own profile

### PR DESCRIPTION
**Pull request by gc**
Implements ability to preview your profile. Just simply views your profile as you would anyone elses, and hides a couple things if you're seeing your own. Tested on web

Closes https://github.com/duolicious/duolicious-frontend/issues/264
Relates to https://github.com/duolicious/duolicious-frontend/issues/137

chrome_OCmpf21lI9

### CODE REVIEW

**Comment by duogenesis** [comment]
This is awesome! I haven't tested it, but do you also need to hide the 'skip' and 'message' buttons from view?

I'm also thinking the button should look like a button and appear after the fields to enter your details instead of at the top

**Comment by gc** [comment]
>do you also need to hide the 'skip' and 'message' buttons from view?
There is no skip/message buttons on the prospect-profile screen as far as I can see.

>I'm also thinking the button should look like a button and appear after the fields to enter your details instead of at the top
I went with the Alert thing to try to be consistent with the Alert in the search tab. I was thinking people might have a harder time finding/seeing it down there too. Whatever you think is best though. I could make it a regular button (Above the "Support Duolicious?), or a component matching the Sign Out/ Deactivate My Account buttons for consistency (below the supportduolicious). Just let me know exactly how you want it

**Comment by duogenesis** [comment]
>There is no skip/message buttons on the prospect-profile screen as far as I can see.

:ok_hand:

>or a component matching the Sign Out/ Deactivate My Account buttons for consistency (below the supportduolicious)

That sounds good. Could you also make it purple? The 'Clubs' section is the last thing someone will fill-in about their profile, so the button should go below that, I'd say.

**Comment by gc** [comment]
Done 
image

**Comment by duogenesis** [comment]
Looking pretty good. Could you replace the icon with a right chevron, like on the other buttons? Could you also capitalize "Your"? After that, I think we're good to merge.

**Comment by gc** [comment]
image

**Comment by duogenesis** [comment]
Thanks! I just checked it out and ran it locally. Something I noticed is that without the `DonutChart`, the height of its parent `View` is a bit smaller than usual. To fix it, you could leave the chart in, but make it transparent when `isViewingSelf`. Also conditionally set `onPress` or `null` or `undefined` so that it's no longer pressable. *Then*, I think we can merge this PR.

**Comment by duogenesis** [comment]
Thanks for working on this, btw. Lots of people asked for this and #137. People are gonna love it

**Comment by gc** [comment]
done

**Pull request merged**
